CREATE DATABASE QLSV
GO

USE QLSV
GO

CREATE TABLE SINH_VIEN
(
	MSSV INT IDENTITY PRIMARY KEY,
	Ho_Ten NVARCHAR(50) NOT NULL,
	Ngay_Sinh DATE NOT NULL,
	Gioi_Tinh NVARCHAR(5) NOT NULL,
	Que_Quan NVARCHAR(100) NOT NULL,
	Dia_Chi NVARCHAR(100) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	SDT INT NOT NULL,
	Status NVARCHAR(20) NOT NULL
)
GO

CREATE TABLE GIAO_VIEN
(
	Ma_GV VARCHAR(20) PRIMARY KEY,
	Ho_Ten NVARCHAR(50) NOT NULL,
	Ngay_Sinh DATE NOT NULL,
	Gioi_Tinh NVARCHAR(5) NOT NULL,
	Que_Quan NVARCHAR(100) NOT NULL,
	Dia_Chi NVARCHAR(100) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	SDT INT NOT NULL,
	Trinh_Do NVARCHAR(30) NOT NULL,
)
GO

CREATE TABLE KHOA
(
	Ma_Khoa VARCHAR(10) PRIMARY KEY,
	Ten_Khoa NVARCHAR(30) NOT NULL
)
GO

CREATE TABLE LOP_HOC
(
	Ma_Lop VARCHAR(10) PRIMARY KEY,
	Ten_Lop NVARCHAR(30) NOT NULL 
)
GO

CREATE TABLE HOC_PHAN
(
	Ma_HP VARCHAR(10) NOT null,
	Ten_HP NVARCHAR(30) NOT NULL,
	So_TC INT NOT NULL,
	
)
GO
