CREATE DATABASE QLBONGDA
GO

USE QLBONGDA
GO

CREATE TABLE CAUTHU
(
	MACT NUMERIC IDENTITY(1,1) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL ,
	NGAYSINH DATETIME ,
	DIACHI NVARCHAR(200) ,
	MACLB VARCHAR(5) NOT NUll, 
	MAQG VARCHAR(5) NOT NULL,
	VITRI NVARCHAR(20) NOT NULL ,
	SO INT NOT NULL  

)
GO

CREATE TABLE QUOCGIA
(
	MAQG VARCHAR(5) PRIMARY KEY,
	TENQG NVARCHAR(60) NOT NULL,
)
GO

CREATE TABLE CAULACBO
(
	MACLB VARCHAR(5) PRIMARY KEY,
	TENCLB NVARCHAR(100) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	MATINH VARCHAR(5) NOT NULL
)
GO

CREATE TABLE TINH
(
	MATINH VARCHAR(5) PRIMARY KEY,
	TENTINH NVARCHAR(100) NOT NULL
)
GO

CREATE TABLE SANVD
(
	MASAN VARCHAR(5) PRIMARY KEY,
	TENSAN NVARCHAR(100) NOT NULL,
	DIACHI NVARCHAR(200)
)
GO

CREATE TABLE HUANLUYENVIEN 
(
	MAHLV VARCHAR(5) PRIMARY KEY,
	TENHLV NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME ,
	DIACHI NVARCHAR(200),
	DIENTHOAI NVARCHAR(20),
	MAQG VARCHAR(5) NOT NULL
)
GO

CREATE TABLE HLV_CLB
(
	MAHLV VARCHAR(5),
	MACLB VARCHAR(5),
	VAITRO NVARCHAR(100) NOT NULL,
	PRIMARY KEY (MAHLV, MACLB)
)
GO

CREATE TABLE TRANDAU
(
	MATRAN NUMERIC IDENTITY(1,1) PRIMARY KEY,
	NAM INT NOT NULL,
	VONG INT NOT NULL,
	NGAYTB DATETIME NOT NULL,
	MACLB1 VARCHAR(5) NOT NULL,
	MACLB2 VARCHAR(5) NOT NULL,
	MASAN VARCHAR(5) NOT NULL,
	KETQUA VARCHAR(5) NOT NULL
)
GO

CREATE TABLE BANGXH
(
	MACLB VARCHAR(5),
	NAM INT ,
	VONG INT ,
	SOTRAN INT NOT NULL,
	THANG INT NOT NULL,
	HOA INT NOT NULL,
	THUA INT NOT NULL,
	HIEUSO VARCHAR(5) NOT NULL,
	DIEM INT NOT NULL,
	HANG INT NOT NULL
	PRIMARY KEY (MACLB, NAM, VONG)
)
GO

ALTER TABLE dbo.CAUTHU
ADD CONSTRAINT FK1_CAUTHU FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB),
	CONSTRAINT FK2_CAUTHU FOREIGN KEY(MAQG) REFERENCES dbo.QUOCGIA(MAQG)


ALTER TABLE dbo.CAULACBO
ADD CONSTRAINT FK1_CLB FOREIGN KEY(MASAN) REFERENCES dbo.SANVD(MASAN),
	CONSTRAINT FK2_CLB FOREIGN KEY(MATINH) REFERENCES dbo.TINH(MATINH)

ALTER TABLE dbo.HUANLUYENVIEN
ADD CONSTRAINT FK_HLV FOREIGN KEY(MAQG) REFERENCES dbo.QUOCGIA(MAQG)

ALTER TABLE dbo.HLV_CLB
ADD CONSTRAINT FK1_HLV_CLB FOREIGN KEY(MAHLV) REFERENCES dbo.HUANLUYENVIEN(MAHLV),
	CONSTRAINT FK2_HLV_CLB FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB)

ALTER TABLE dbo.TRANDAU
ADD CONSTRAINT FK1_MATCH FOREIGN KEY(MACLB1) REFERENCES dbo.CAULACBO(MACLB),
	CONSTRAINT FK2_MATCH FOREIGN KEY(MACLB2) REFERENCES dbo.CAULACBO(MACLB),
	CONSTRAINT FK3_MATCH FOREIGN KEY(MASAN) REFERENCES dbo.SANVD(MASAN)

ALTER TABLE dbo.BANGXH
ADD CONSTRAINT FK1_XH FOREIGN KEY(MACLB) REFERENCES dbo.CAULACBO(MACLB)


INSERT INTO dbo.CAUTHU
(
    HOTEN,
    NGAYSINH,
    DIACHI,
    MACLB,
    MAQG,
    VITRI,
    SO
)
VALUES
(   N'Nguyễn Vũ Phong',       -- HOTEN
    19900220, -- NGAYSINH
    N'',       -- DIACHI
    'BBD',        -- MACLB
    'VN',        -- MAQG
    'Tiền vệ',        -- VITRI
    17          -- SO
    )
INSERT INTO dbo.CAUTHU
(
    HOTEN,
    NGAYSINH,
    DIACHI,
    MACLB,
    MAQG,
    VITRI,
    SO
)
VALUES
(   N'Nguyễn Công Vinh',       -- HOTEN
    19920310, -- NGAYSINH
    N'',       -- DIACHI
    'HAGL',        -- MACLB
    'VN',        -- MAQG
    'Tiền đạo',        -- VITRI
    9          -- SO
    )
INSERT INTO dbo.CAUTHU
(
    HOTEN,
    NGAYSINH,
    DIACHI,
    MACLB,
    MAQG,
    VITRI,
    SO
)
VALUES
(   N'Trần Tấn Tài',       -- HOTEN
    19891112, -- NGAYSINH
    N'',       -- DIACHI
    'BBD',        -- MACLB
    'VN',        -- MAQG
    'Tiền vệ',        -- VITRI
    8          -- SO
    )